[package]
name = "day-1"
version = "0.1.0"
edition = "2021"

[dependencies]
# Inherit dependencies from workspace
# <dependency>.workspace = true
rayon.workspace = true
clap = { version = "4.5.53", features = ["derive"] }
